
// constants for the login request

export const GET_LOGIN_REQUEST = 'GET_LOGIN_REQUEST';
export const GET_LOGIN_SUCCESS = 'GET_LOGIN_SUCCESS';
export const GET_LOGIN_REJECT= 'GET_LOGIN_REJECT';

/* WE WILL GET THE USER'S DETAILS ON EVERY REQUEST ON THE APPLICATION */

export const GET_USER_DETAILS_REQUEST = 'GET_USER_DETAILS_REQUEST';
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_REJECT = 'GET_USER_DETAILS_REJECT';


