
export const ADD_TO_SCHEDULE_CART = 'ADD_TO_SCHEDULE_CART';
export const REMOVE_TO_SCHEDULE_CART = 'REMOVE_TO_SCHEDULE_CART';
export const RESET_TO_SCHEDULE_CART = 'RESET_TO_SCHEDULE_CART';
export const SEND_SCHEDULE_CART_TO_ADMIN = 'SEND_SCHEDULE_CART_TO_ADMIN';

