
export const GET_SCHEDULE_REQUEST = 'GET_SCHEDULE_REQUEST';
export const GET_SCHEDULE_SUCCESS = 'GET_SCHEDULE_SUCCESS';
export const GET_SCHEDULE_FAILURE = 'GET_SCHEDULE_FAILURE';

export const GET_SHIFT_DETAILS_REQUEST = 'GET_SHIFT_DETAILS_REQUEST';
export const GET_SHIFT_DETAILS_SUCCESS = 'GET_SHIFT_DETAILS_SUCCESS';
export const GET_SHIFT_DETAILS_FAILURE = 'GET_SHIFT_DETAILS_FAILURE';

/* _____THIS___IS____FOR ___RESETING___THE____ENTIRE___STATE_____*/
// PLEASE BE CAREFUL AS THE ENTIRE ARRAY WOULD BE RESET TO EMPTY ARRAY

export const GET_SHIFT_DETAILS_RESET = 'GET_SHIFT_DETAILS_RESET';